[package]
name = "genai-tools-macros"
version = "0.3.5"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Proc macros for genai-tools"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[lib]
proc-macro = true 
